(() => {
  "use strict";

  const countries = [
    "Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burundi","Cabo Verde","Cambodia","Cameroon","Canada","Central African Republic","Chad","Chile","China","Colombia","Comoros","Costa Rica","Croatia","Cuba","Cyprus","Czech Republic","Democratic Republic of the Congo","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia","Fiji","Finland","France","Gabon","Gambia","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Ivory Coast","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Korea","North Macedonia","Norway","Oman","Pakistan","Palau","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Republic of the Congo","Romania","Russia","Rwanda","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines","Samoa","San Marino","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia","Solomon Islands","Somalia","South Africa","South Korea","South Sudan","Spain","Sri Lanka","Sudan","Suriname","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan","Vanuatu","Vatican City","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe"
  ];

  const cities = {
    Greece:["Athens","Thessaloniki","Patras","Heraklion","Larissa","Volos","Ioannina","Chania","Rhodes","Kalamata","Kavala","Serres","Alexandroupoli","Trikala","Corfu","Agrinio","Chalkida","Katerini","Xanthi","Rethymno"],
    Cyprus:["Nicosia","Limassol","Larnaca","Paphos","Famagusta","Kyrenia"],
    Italy:["Rome","Milan","Naples","Turin","Palermo","Genoa","Bologna","Florence","Bari","Venice","Verona","Catania"],
    France:["Paris","Marseille","Lyon","Toulouse","Nice","Nantes","Montpellier","Strasbourg","Bordeaux","Lille"],
    Germany:["Berlin","Hamburg","Munich","Cologne","Frankfurt","Stuttgart","Düsseldorf","Leipzig","Dortmund","Bremen"],
    Spain:["Madrid","Barcelona","Valencia","Seville","Zaragoza","Málaga","Murcia","Palma","Bilbao","Alicante"],
    Portugal:["Lisbon","Porto","Braga","Coimbra","Funchal","Aveiro","Faro","Setúbal"],
    "United Kingdom":["London","Birmingham","Manchester","Glasgow","Liverpool","Leeds","Edinburgh","Bristol","Cardiff","Belfast"],
    Ireland:["Dublin","Cork","Limerick","Galway","Waterford","Kilkenny"],
    Netherlands:["Amsterdam","Rotterdam","The Hague","Utrecht","Eindhoven","Groningen"],
    Belgium:["Brussels","Antwerp","Ghent","Charleroi","Liège","Bruges"],
    Switzerland:["Zurich","Geneva","Basel","Lausanne","Bern","Lucerne"],
    Austria:["Vienna","Graz","Linz","Salzburg","Innsbruck","Klagenfurt"],
    Poland:["Warsaw","Kraków","Łódź","Wrocław","Poznań","Gdańsk","Szczecin"],
    Romania:["Bucharest","Cluj-Napoca","Timișoara","Iași","Constanța","Brașov"],
    Bulgaria:["Sofia","Plovdiv","Varna","Burgas","Ruse","Stara Zagora"],
    Serbia:["Belgrade","Novi Sad","Niš","Kragujevac","Subotica"],
    Croatia:["Zagreb","Split","Rijeka","Osijek","Zadar","Dubrovnik"],
    Albania:["Tirana","Durrës","Vlorë","Shkodër","Elbasan","Korçë"],
    Turkey:["Istanbul","Ankara","Izmir","Bursa","Antalya","Adana","Konya","Gaziantep"],
    Sweden:["Stockholm","Gothenburg","Malmö","Uppsala","Västerås"],
    Norway:["Oslo","Bergen","Trondheim","Stavanger","Tromsø"],
    Finland:["Helsinki","Espoo","Tampere","Vantaa","Turku","Oulu"],
    Denmark:["Copenhagen","Aarhus","Odense","Aalborg","Esbjerg"],
    Ukraine:["Kyiv","Kharkiv","Odesa","Dnipro","Lviv","Zaporizhzhia"],
    Russia:["Moscow","Saint Petersburg","Novosibirsk","Yekaterinburg","Kazan","Sochi"],
    "United States":["New York","Los Angeles","Chicago","Houston","Phoenix","Philadelphia","San Antonio","San Diego","Dallas","Miami","Boston","Seattle","San Francisco"],
    Canada:["Toronto","Montreal","Vancouver","Calgary","Edmonton","Ottawa","Winnipeg","Quebec City"],
    Mexico:["Mexico City","Guadalajara","Monterrey","Puebla","Tijuana","Cancún"],
    Brazil:["São Paulo","Rio de Janeiro","Brasília","Salvador","Fortaleza","Belo Horizonte","Curitiba"],
    Argentina:["Buenos Aires","Córdoba","Rosario","Mendoza","La Plata","Mar del Plata"],
    Chile:["Santiago","Valparaíso","Concepción","Antofagasta","Viña del Mar"],
    Colombia:["Bogotá","Medellín","Cali","Barranquilla","Cartagena"],
    Peru:["Lima","Arequipa","Trujillo","Cusco","Chiclayo"],
    Australia:["Sydney","Melbourne","Brisbane","Perth","Adelaide","Canberra","Gold Coast"],
    "New Zealand":["Auckland","Wellington","Christchurch","Hamilton","Tauranga","Dunedin"],
    Japan:["Tokyo","Yokohama","Osaka","Nagoya","Sapporo","Fukuoka","Kyoto","Kobe"],
    China:["Beijing","Shanghai","Guangzhou","Shenzhen","Chengdu","Wuhan","Xi'an","Hangzhou"],
    India:["Delhi","Mumbai","Bengaluru","Hyderabad","Chennai","Kolkata","Pune","Ahmedabad"],
    "South Korea":["Seoul","Busan","Incheon","Daegu","Daejeon","Gwangju"],
    Thailand:["Bangkok","Chiang Mai","Phuket","Pattaya","Khon Kaen"],
    Indonesia:["Jakarta","Surabaya","Bandung","Medan","Semarang","Bali"],
    Philippines:["Manila","Quezon City","Davao City","Cebu City","Makati"],
    Singapore:["Singapore"],
    Malaysia:["Kuala Lumpur","George Town","Johor Bahru","Ipoh","Kota Kinabalu"],
    "South Africa":["Johannesburg","Cape Town","Durban","Pretoria","Port Elizabeth"],
    Egypt:["Cairo","Alexandria","Giza","Luxor","Aswan"],
    Morocco:["Casablanca","Rabat","Marrakesh","Fes","Tangier","Agadir"],
    Israel:["Jerusalem","Tel Aviv","Haifa","Beersheba","Eilat"],
    "United Arab Emirates":["Dubai","Abu Dhabi","Sharjah","Ajman","Al Ain"],
    "Saudi Arabia":["Riyadh","Jeddah","Mecca","Medina","Dammam"],
    Lebanon:["Beirut","Tripoli","Sidon","Byblos","Zahle"],
    Jordan:["Amman","Zarqa","Irbid","Aqaba","Madaba"],
    Pakistan:["Karachi","Lahore","Islamabad","Rawalpindi","Faisalabad","Peshawar"],
    Hungary:["Budapest","Debrecen","Szeged","Miskolc","Pécs"],
    "Czech Republic":["Prague","Brno","Ostrava","Plzeň","Liberec"],
    Slovakia:["Bratislava","Košice","Prešov","Žilina","Nitra"],
    Slovenia:["Ljubljana","Maribor","Kranj","Koper","Celje"],
    Estonia:["Tallinn","Tartu","Narva","Pärnu"],
    Latvia:["Riga","Daugavpils","Liepāja","Jelgava"],
    Lithuania:["Vilnius","Kaunas","Klaipėda","Šiauliai"],
    Iceland:["Reykjavík","Kópavogur","Hafnarfjörður","Akureyri"],
    Malta:["Valletta","Birkirkara","Sliema","St. Julian's"],
    Georgia:["Tbilisi","Batumi","Kutaisi","Rustavi"],
    Armenia:["Yerevan","Gyumri","Vanadzor"],
    Kazakhstan:["Almaty","Astana","Shymkent","Karaganda"],
    Vietnam:["Ho Chi Minh City","Hanoi","Da Nang","Hai Phong","Can Tho"],
    Taiwan:["Taipei","Kaohsiung","Taichung","Tainan"],
    "Sri Lanka":["Colombo","Kandy","Galle","Jaffna"],
    Bangladesh:["Dhaka","Chittagong","Khulna","Rajshahi"],
    Nepal:["Kathmandu","Pokhara","Lalitpur","Biratnagar"],
    Kenya:["Nairobi","Mombasa","Kisumu","Nakuru"],
    Nigeria:["Lagos","Abuja","Kano","Ibadan","Port Harcourt"],
    Tunisia:["Tunis","Sfax","Sousse","Kairouan"],
    Algeria:["Algiers","Oran","Constantine","Annaba"],
    "North Macedonia":["Skopje","Bitola","Kumanovo","Ohrid"],
    Montenegro:["Podgorica","Nikšić","Budva","Kotor"]
  };

  window.ThePetGridLocationData = { countries, cities };
})();
