import { dom } from "./dom.js"; import { state,activeConversation } from "./state.js"; import { loadData,saveData } from "./data.js"; import { renderConversationList,renderActive,scrollBottom } from "./render.js"; import { send,updateComposer,resize,selectAttachment,clearAttachment } from "./composer.js";
function renderAll(){renderConversationList(openConversation);renderActive();updateComposer();}
function openConversation(id){const c=state.conversations.find(x=>String(x.id)===String(id));if(!c)return;state.activeConversationId=c.id;c.messages.forEach(m=>m.read=true);saveData();renderAll();scrollBottom(false);dom.messageInput?.focus();}
function bind(){dom.messageComposerForm?.addEventListener("submit",e=>{e.preventDefault();send(()=>{renderConversationList(openConversation);renderActive();scrollBottom(true);});});dom.messageInput?.addEventListener("input",()=>{resize();updateComposer();});dom.messageInput?.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();dom.messageComposerForm?.requestSubmit();}});dom.attachmentButton?.addEventListener("click",()=>dom.attachmentInput?.click());dom.attachmentInput?.addEventListener("change",()=>selectAttachment(dom.attachmentInput.files?.[0]));dom.removeAttachmentButton?.addEventListener("click",clearAttachment);dom.scrollToLatestButton?.addEventListener("click",()=>scrollBottom(true));dom.conversationSearchInput?.addEventListener("input",()=>{state.conversationSearch=dom.conversationSearchInput.value;renderConversationList(openConversation);});dom.clearConversationSearch?.addEventListener("click",()=>{dom.conversationSearchInput.value="";state.conversationSearch="";renderConversationList(openConversation);});
 const emojis=["😀","😂","😍","🥰","😊","😢","❤️","🐾","🐶","🐱","🎉","👍"];
 if(dom.emojiGrid){dom.emojiGrid.innerHTML=emojis.map(x=>`<button type="button" class="emoji-option">${x}</button>`).join("");dom.emojiGrid.addEventListener("click",e=>{const b=e.target.closest("button");if(!b||!dom.messageInput)return;dom.messageInput.value+=b.textContent;dom.emojiPicker.hidden=true;updateComposer();dom.messageInput.focus();});}
 dom.emojiButton?.addEventListener("click",()=>{if(dom.emojiPicker)dom.emojiPicker.hidden=!dom.emojiPicker.hidden;});dom.closeEmojiPicker?.addEventListener("click",()=>{if(dom.emojiPicker)dom.emojiPicker.hidden=true;});
}
loadData();bind();renderAll();const first=state.conversations.find(c=>!c.archived);if(first)openConversation(first.id);
